include: package:lints/recommended.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
  exclude:
    - '**.mocks.dart'
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - cancel_subscriptions
    - unawaited_futures
    - always_declare_return_types
    - prefer_final_fields
    - prefer_final_in_for_each
