name: impaktfull_cli
description: A cli that combines all tools for development, testing, ci/cd,...
version: 0.0.1
repository: https://github.com/impaktfull/impaktfull_cli

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  http: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
