name: Automated version bump

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  bump_version:
    name: Version bump on main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Automated version bump
        uses: impaktfull/gh_action_dart_conventional_release@main
        with:
          tag-prefix: "v"
          use-dart: true
          deploy-key: ${{ secrets.IMPAKTFULL_DEPLOY_KEY }}
