name: Automated version bump

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    name: Version bump on main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}  
      - name: cat pubspec.yaml
        run: cat ./pubspec.yaml
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Automated version bump
        uses: impaktfull/gh_action_dart_conventional_release@v0.1.11
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: cat pubspec.yaml
        run: cat ./pubspec.yaml
